Add charts/ empty folder
Should avoid
```
Error: mkdir /tmp/elife-xpub-formula/helm/elife-xpub/charts: permission
denied
```
due to the clash between the `jenkins` owner and the `elife` user
running `helm` commands.